name: ci

on:
  pull_request:
  push:
    branches:
      - hml
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: test net/http module
        run: go test ./...
      - name: test gin module
        working-directory: gin
        run: go test ./...
